const citiesArr: { en: string; ar: string }[] = [
  { en: "Adana", ar: "أضنة" },
  { en: "Adıyaman", ar: "أديامان" },
  { en: "Afyonkarahisar", ar: "أفيون قرة حصار" },
  { en: "Ağrı", ar: "أغري" },
  { en: "Aksaray", ar: "أكسراي" },
  { en: "Amasya", ar: "أماسيا" },
  { en: "Ankara", ar: "أنقرة" },
  { en: "Antalya", ar: "أنطاليا" },
  { en: "Ardahan", ar: "أرداهان" },
  { en: "Artvin", ar: "أرتفين" },
  { en: "Aydın", ar: "أيدين" },
  { en: "Balıkesir", ar: "بالكسير" },
  { en: "Bartın", ar: "بارتين" },
  { en: "Batman", ar: "باتمان" },
  { en: "Bayburt", ar: "بايبورت" },
  { en: "Bilecik", ar: "بيليجيك" },
  { en: "Bingöl", ar: "بينغول" },
  { en: "Bitlis", ar: "بتليس" },
  { en: "Bolu", ar: "بولو" },
  { en: "Burdur", ar: "بوردر" },
  { en: "Bursa", ar: "بورصة" },
  { en: "Çanakkale", ar: "جناق قلعة" },
  { en: "Çankırı", ar: "تشكر" },
  { en: "Çorum", ar: "تشوروم" },
  { en: "Denizli", ar: "دينيزلي" },
  { en: "Diyarbakır", ar: "ديار بكر" },
  { en: "Düzce", ar: "دوزجة" },
  { en: "Edirne", ar: "أدرنة" },
  { en: "Elazığ", ar: "إلازيغ" },
  { en: "Erzincan", ar: "أرضروم" },
  { en: "Erzurum", ar: "أرضروم" },
  { en: "Eskişehir", ar: "إسكي شهير" },
  { en: "Gaziantep", ar: "غازي عنتاب" },
  { en: "Giresun", ar: "غيرسون" },
  { en: "Gümüşhane", ar: "غوموشانه" },
  { en: "Hakkari", ar: "هكاري" },
  { en: "Hatay", ar: "حطاي" },
  { en: "Iğdır", ar: "إغدير" },
  { en: "Isparta", ar: "إسبارطة" },
  { en: "İstanbul", ar: "اسطنبول" },
  { en: "İzmir", ar: "إزمير" },
  { en: "Kahramanmaraş", ar: "قهرمان مرعش" },
  { en: "Karabük", ar: "كارابوك" },
  { en: "Karaman", ar: "قرمان" },
  { en: "Kars", ar: "قارس" },
  { en: "Kastamonu", ar: "كاستامونو" },
  { en: "Kayseri", ar: "قيصري" },
  { en: "Kırıkkale", ar: "قرقل" },
  { en: "Kırklareli", ar: "قرقلاريلي" },
  { en: "Kırşehir", ar: "قير شهير" },
  { en: "Kilis", ar: "كيليس" },
  { en: "Konya", ar: "قونية" },
  { en: "Kocaeli", ar: "قوجالي" },
  { en: "Malatya", ar: "ملطية" },
  { en: "Manisa", ar: "مانيسا" },
  { en: "Mardin", ar: "ماردين" },
  { en: "Mersin", ar: "مرسين" },
  { en: "Muğla", ar: "موغلا" },
  { en: "Muş", ar: "موش" },
  { en: "Nevşehir", ar: "نوشهر" },
  { en: "Niğde", ar: "نيغدة" },
  { en: "Ordu", ar: "أوردو" },
  { en: "Osmaniye", ar: "عطية" },
  { en: "Rize", ar: "ريزا" },
  { en: "Sakarya", ar: "ساكاريا" },
  { en: "Samsun", ar: "سامسون" },
  { en: "Şanlıurfa", ar: "شانلي أورفا" },
  { en: "Siirt", ar: "سيرت" },
  { en: "Sinop", ar: "سينوب" },
  { en: "Sivas", ar: "سيفاس" },
  { en: "Şırnak", ar: "شرناق" },
  { en: "Tekirdağ", ar: "تكييرداغ" },
  { en: "Tokat", ar: "توكات" },
  { en: "Trabzon", ar: "طرابزون" },
  { en: "Tunceli", ar: "تونجلي" },
  { en: "Uşak", ar: "أوشاق" },
  { en: "Van", ar: "فان" },
  { en: "Yalova", ar: "يالوفا" },
  { en: "Yozgat", ar: "يوزغات" },
  { en: "Zonguldak", ar: "زونغولداك" },
];

export default citiesArr;
